---


image: registry.gitlab.com/src_prepare/gentoo-repoman-container:latest


stages:
  - test


before_script:
  - emerge --sync --quiet


test:
  stage: test
  timeout: 20 minutes

  script:
    - make deps-versions
    - make test
