---


# Copyright (c) 2019-2022, Maciej Barć <xgqt@riseup.net>
# Licensed under the GNU GPL v2 License


image: registry.gitlab.com/src_prepare/gentoo-repoman-container:latest


variables:
  GIT_SUBMODULE_STRATEGY: "recursive"


stages:
  - test


test:
  stage: test
  script:
    - bash scripts/repomanci
