image: gentoo/stage3-amd64:latest

stages:
  - test

before_script:
  - mkdir -p /var/cache/distfiles
  - mkdir -p /var/db/repos/gentoo
  - emerge-webrsync
  - git clone https://gitlab.com/src_prepare/scripts.git /scripts
  - cp /scripts/src/check-commit /usr/bin

test:
  stage: test
  script:
    - check-commit
