---


image: registry.gitlab.com/src_prepare/gentoo-repoman-container:latest


stages:
  - test


before_script:
  - emerge --sync


test:
  stage: test

  script:
    - make deps-versions
    - make test
