---
image: docker.io/xgqt/ci-gentoo-tools:3.0.0.current-glibc

stages:
  - test

test:
  stage: test
  timeout: 20 minutes
  script:
    - export FEATURES="-sandbox" && scons build
    - export FEATURES="-sandbox" && scons test
