image: gentoo/stage3-amd64:latest

stages:
  - test

before_script:
  - mkdir -p /var/cache/distfiles
  - mkdir -p /var/db/repos/gentoo
  - emerge-webrsync
  - emerge -q --jobs=8 --noreplace app-portage/repoman net-misc/wget
  - wget "https://gitlab.com/src_prepare/scripts/-/raw/master/src/repomanci" -O /usr/bin/repomanci
  - chmod 777 /usr/bin/repomanci

test:
  stage: test
  script:
    - repomanci
