---

image: docker.io/xgqt/ci-gentoo-tools:amd64-nomultilib-openrc-1.0.0.2023.11.05.23.14

stages:
  - test

test:
  stage: test
  timeout: 20 minutes

  script:
    - make deps-versions
    - make test
