---


# Copyright (c) 2019-2022, Maciej Barć <xgqt@riseup.net>
# Licensed under the GNU GPL v2 License


image: registry.gitlab.com/src_prepare/gentoo-repoman-container:latest


stages:
  - test


test:
  stage: test

  before_script:
    - make deps-versions

  script:
    - make test
