---
image: docker.io/xgqt/ci-gentoo-tools:latest

stages:
  - test

test:
  stage: test
  timeout: 20 minutes

  script:
    - egencache --jobs 16 --load-average 2 --update
    - make deps-versions
    - make test
