# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-vcs-permalinks
      - id: end-of-file-fixer

      - id: check-json
      - id: check-xml
      - id: check-yaml

      - id: trailing-whitespace
        exclude: ".*\\.patch$"

      - id: pretty-format-json
        args: ["--autofix", "--indent", "2", "--no-sort-keys"]
