#!/bin/sh


# Original author: XGQT (xgqt@protonmail.com)

# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2


meta_dir="./metadata/md5-cache"


if [ -d "${meta_dir}" ]
then
    if ! rm -dfr "${meta_dir}"
    then
        sudo rm -dfr "${meta_dir}" || exit 1
    fi
else
    echo "No pre-generated metadata found in ${meta_dir}"
fi
