#!/bin/sh


# Original author: XGQT (xgqt@protonmail.com)

# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2


trap 'exit 128' INT
export PATH


if command -v qmacs >/dev/null 2>&1
then
    EDITOR="qmacs"
    export EDITOR
fi

FEATURES="sign"
export FEATURES


git add .

if [ -z "${1}" ]
then
    repoman commit
else
    repoman commit -m "${*}"
fi

git pull --verbose
git push --verbose
