#!/bin/sh


# Original author: XGQT (xgqt@protonmail.com)

# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2


trap 'exit 1' INT
export PATH


script_dir="$(dirname "${0}")"


sh "${script_dir}"/clean-metadata || exit 1

repoman fix && repoman -Idx full && pkgcheck scan
